name: reloj_esp32
description: "App móvil Flutter Material 3 para controlar por BLE un reloj de pared ESP32-C3 con 58 LEDs WS2812B."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.3.13
  provider: ^6.1.2
  intl: ^0.20.3
  flutter_colorpicker: ^1.1.0
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  ios: false

flutter:
  uses-material-design: true
